# Generated by Django 4.2 on 2024-10-20 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('latitude', models.CharField(blank=True, max_length=25, null=True, unique=True)),
                ('longitude', models.CharField(blank=True, max_length=25, null=True, unique=True)),
                ('status', models.SmallIntegerField(choices=[(0, 0), (1, 1)], db_column='status', default=1)),
                ('createdDate', models.DateTimeField(db_column='created_date', default=django.utils.timezone.now)),
                ('updatedDate', models.DateTimeField(db_column='updated_date', default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(db_column='id', db_index=True, primary_key=True, serialize=False)),
                ('category', models.CharField(db_column='category', max_length=1000, null=True)),
                ('code', models.CharField(db_column='code', max_length=100, null=True)),
                ('path', models.CharField(blank=True, db_column='path', max_length=250, null=True)),
                ('level', models.IntegerField(db_column='level', default=0)),
                ('childrenCount', models.IntegerField(db_column='children_count', default=0)),
                ('mediaPaths', models.CharField(blank=True, db_column='media_paths', max_length=250, null=True)),
                ('status', models.SmallIntegerField(choices=[(0, 0), (1, 1)], db_column='status', default=1)),
                ('createdDate', models.DateTimeField(db_column='created_date', default=django.utils.timezone.now)),
                ('updatedDate', models.DateTimeField(db_column='updated_date', default=django.utils.timezone.now)),
                ('parentId', models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.categories')),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderStatus',
            fields=[
                ('id', models.AutoField(db_column='id', db_index=True, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, db_column='code', max_length=50, null=True, unique=True)),
                ('buyerStatus', models.CharField(blank=True, db_column='buyer_status', max_length=150, null=True)),
                ('buyerColorCode', models.CharField(blank=True, db_column='buyer_color_code', max_length=20, null=True)),
                ('sellerStatus', models.CharField(blank=True, db_column='seller_status', max_length=150, null=True)),
                ('sellerColorCode', models.CharField(blank=True, db_column='seller_color_code', max_length=150, null=True)),
                ('createdDate', models.DateTimeField(db_column='created_date', default=django.utils.timezone.now)),
                ('updatedDate', models.DateTimeField(auto_now=True, db_column='updated_date')),
            ],
            options={
                'db_table': 'po_status',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='createdDate',
            field=models.DateTimeField(db_column='created_date', default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 0), (1, 1)], db_column='status', default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='updatedDate',
            field=models.DateTimeField(db_column='updated_date', default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, db_index=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(db_column='id', db_index=True, primary_key=True, serialize=False)),
                ('sku', models.CharField(blank=True, db_column='sku', max_length=255, null=True)),
                ('productName', models.CharField(blank=True, db_column='product_name', db_index=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('mediaPaths', models.CharField(blank=True, db_column='media_paths', max_length=255, null=True)),
                ('stock', models.IntegerField(blank=True, db_column='stock', null=True)),
                ('price', models.CharField(blank=True, db_column='price', max_length=25, null=True)),
                ('minSaleQty', models.IntegerField(blank=True, db_column='min_sal_qty', default=1, null=True)),
                ('attributes', models.JSONField(blank=True, db_column='attributes', db_index=True, null=True)),
                ('status', models.SmallIntegerField(choices=[(0, 0), (1, 1)], db_column='status', default=1)),
                ('createdDate', models.DateTimeField(db_column='created_date', default=django.utils.timezone.now)),
                ('updatedDate', models.DateTimeField(db_column='updated_date', default=django.utils.timezone.now)),
                ('categoryId', models.ForeignKey(blank=True, db_column='category_ids', null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.categories')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(db_column='id', db_index=True, primary_key=True, serialize=False)),
                ('orderNumber', models.CharField(blank=True, db_column='po_number', max_length=50, null=True, unique=True)),
                ('PoCreatedDate', models.DateField(blank=True, db_column='po_created_date', null=True)),
                ('paymentMode', models.CharField(blank=True, db_column='payment_mode', max_length=50, null=True)),
                ('cancelReason', models.CharField(blank=True, db_column='cancel_reason', max_length=1000, null=True)),
                ('totalQty', models.IntegerField(blank=True, db_column='total_qty', default=0, null=True)),
                ('totalAmount', models.FloatField(blank=True, db_column='total_amount', default=0, null=True)),
                ('createdDate', models.DateTimeField(db_column='created_date', default=django.utils.timezone.now)),
                ('updatedDate', models.DateTimeField(auto_now=True, db_column='updated_date')),
                ('billingAddress', models.ForeignKey(db_column='billing_address', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='po_billing_address', to='store.address')),
                ('shippingAddress', models.ForeignKey(db_column='shipping_address', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='po_shipping_address', to='store.address')),
                ('status', models.ForeignKey(db_column='status', null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.purchaseorderstatus')),
                ('userId', models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'order_details',
            },
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.AutoField(db_column='id', db_index=True, primary_key=True, serialize=False)),
                ('qty', models.IntegerField(blank=True, db_column='qty', default=0, null=True)),
                ('unitPrice', models.FloatField(blank=True, db_column='unit_price', default=0, null=True)),
                ('gstPercentage', models.FloatField(blank=True, db_column='gst_percentage', default=0, null=True)),
                ('gst', models.FloatField(blank=True, db_column='gst', default=0, null=True)),
                ('discountPercentage', models.FloatField(blank=True, db_column='discount_percentage', default=0, null=True)),
                ('discount', models.FloatField(blank=True, db_column='discount', default=0, null=True)),
                ('insurance', models.FloatField(blank=True, db_column='insurance', default=0, null=True)),
                ('logistics', models.FloatField(blank=True, db_column='logistics', default=0, null=True)),
                ('shipping', models.FloatField(blank=True, db_column='shipping', default=0, null=True)),
                ('totalAmount', models.FloatField(blank=True, db_column='total_amount', default=0, null=True)),
                ('info', models.JSONField(blank=True, db_column='info', null=True)),
                ('status', models.SmallIntegerField(choices=[(0, 0), (1, 1)], db_column='status', default=1)),
                ('createdDate', models.DateTimeField(db_column='created_date', default=django.utils.timezone.now)),
                ('updatedDate', models.DateTimeField(auto_now=True, db_column='updated_date')),
                ('orderId', models.ForeignKey(db_column='po_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.orders')),
                ('productId', models.ForeignKey(db_column='product_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.products')),
            ],
            options={
                'db_table': 'order_items',
            },
        ),
        migrations.AddField(
            model_name='address',
            name='userId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
