# Generated by Django 4.2 on 2024-10-20 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_address_categories_purchaseorderstatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='info',
            field=models.TextField(blank=True, db_column='info', null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='attributes',
            field=models.TextField(blank=True, db_column='attributes', db_index=True, null=True),
        ),
    ]
