# Generated by Django 4.2 on 2024-10-20 11:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_orderitems_info_alter_products_attributes'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.AutoField(db_column='id', db_index=True, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, db_column='code', max_length=50, null=True, unique=True)),
                ('orderStatus', models.CharField(blank=True, db_column='status', max_length=150, null=True)),
                ('createdDate', models.DateTimeField(db_column='created_date', default=django.utils.timezone.now)),
                ('updatedDate', models.DateTimeField(auto_now=True, db_column='updated_date')),
            ],
            options={
                'db_table': 'order_status',
            },
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.ForeignKey(db_column='status', null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.orderstatus'),
        ),
        migrations.DeleteModel(
            name='PurchaseOrderStatus',
        ),
    ]
