# Generated by Django 4.2 on 2024-10-22 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_products_mediapaths_products_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='attributes',
            field=models.JSONField(blank=True, db_column='attributes', null=True),
        ),
    ]
